name: Actividad 1 Ingesta de Datos

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: windows-latest
    permissions:
      contents: write


    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.9.2'
      - name: paso1 - crea entorno virtual
        run: python -m venv venv
      - name: paso2 - activar entorno virtual
        run: ./venv/Scripts/activate   
      - name: paso3 - actualizar pip
        run: pip install --upgrade pip
      - name: paso4 - instalar dependencias
        run: pip install -e .
      - name: paso5 - Ejecutar script
        run: python src/ingestion.py 

      - name: Pull latest changes from remote
        run: git pull origin main --rebase

      - name: Commit and Push changes
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: entrega actividad 1
          commit_user_name: Jeisson Araque
          commit_user_email: jeisson.araque@est.iudigital.edu.co
          commit_author: Jeisson Araque <jeisson.araque@est.iudigital.edu.co>
